### ISSUE TITLE
blender installation

### ISSUE THREAD

**Issue by thucz** [liuyuan-pal/SyncDreamer#10]
Hi! I wonder how you install blender. Which library do you use? 
`blender --background --python blender_script.py -- \
  --object_path objaverse_examples/6f99fb8c2f1a4252b986ed5a765e1db9/6f99fb8c2f1a4252b986ed5a765e1db9.glb \
  --output_dir ./training_examples/target --camera_type fixed`

**Comment by liuyuan-pal** [comment]
Hi, I use the installation package from the official site.
