### ISSUE TITLE
how can I generate uid_set.pkl for training_examples?

### ISSUE THREAD

**Issue by thucz** [liuyuan-pal/SyncDreamer#11]
I noticed that you have provided uid_set.pkl for example. But I still wonder how can I generate new uid_set.pkl for customized data samples.

**Comment by liuyuan-pal** [comment]
Hi, this line shows how I generate the pkl file https://github.com/liuyuan-pal/SyncDreamer/blob/510262c9081cd34a1f2f34453eefd959c6592833/render_batch.py#L20

**Comment by thucz** [comment]
Thanks a lot!
