### ISSUE TITLE
200 steps for inference sampling will be quite slow.

### ISSUE THREAD

**Issue by seakforzq** [liuyuan-pal/SyncDreamer#12]
I run the inference script for one image on a single piece of V100, but it shows that 7min is needed to generate 4 views. Then I found that the sampling step is 200. I wonder if it is feasible to turn down it as 50 as StableDiffusion does?

**Comment by seakforzq** [comment]
Sorry, It produce four sequences each with 16 views.

**Comment by liuyuan-pal** [comment]
Hi, Thanks for the advice! I've checked that it's feasible to run SyncDreamer for only 50 steps. I've just updated the codes to include the `--sample_steps` parameter.
