### ISSUE TITLE
blender_script renders data very slowly

### ISSUE THREAD

**Issue by thucz** [liuyuan-pal/SyncDreamer#14]
Hello! I would like to use `blender_script` to render input and target views. But it took me more than 3 days to render just 10000 objects. How long does it cost for you to render the whole dataset?

**Comment by liuyuan-pal** [comment]
Hi, the rendering requires a GPU and it needs faster IO of the model file. This could be the bottleneck for the rendering speed. I use about 2 weeks to render 800k models using 8 V100 GPUs.

**Comment by thucz** [comment]
Great thanks! You remind me to use multi-GPU and multi-process.

**Comment by buaacyw** [comment]
Have you solved your problem? @thucz 
Are you using Cycle Engine for rendering?

**Comment by thucz** [comment]
> Hi, @thucz. Have you solved your problem? Are you using Cycle Engine for rendering?

Not completely. Although I used multi-gpu, it still takes a lot of time. I'm using Cycle Engine
