### ISSUE TITLE
super-resolution before reconstruction?

### ISSUE THREAD

**Issue by mdarhdarz** [liuyuan-pal/SyncDreamer#2]
I note that the resolution is limited to 256? Is it possible to apply a super-resolution model like tile-controlnet to obtain high-resolution images and then use neus resconstruction to get a much higher quality 3d generation?

**Comment by liuyuan-pal** [comment]
Hi, the current version only uses a resolution of 256. Increasing the resolution by SR module could be a promising solution but I'm not sure if this would break multiview consistency or not. Maybe, I could give it a try after I clean and release the codes. Thanks for your advice!
