### ISSUE TITLE
在人类模特上面生成的效果很奇怪，是什么原因呢

### ISSUE THREAD

**Issue by PikaCat-OuO** [liuyuan-pal/SyncDreamer#20]
我使用https://huggingface.co/spaces/liuyuan-pal/SyncDreamer
并上传了这张图像作为输入：
![image](https://github.com/liuyuan-pal/SyncDreamer/assets/73384062/cde59511-e021-4ed7-9035-d981e8721020)
Crop size选择了240，Elevation选择了0°
最后生成效果比较奇怪，是因为数据集里面真人的训练数据不足吗？还是模型本身的不足呢，还是说，输入的分辨率比较低
![image](https://github.com/liuyuan-pal/SyncDreamer/assets/73384062/763f0c27-00ab-4253-8651-b5ecd4640f11)

**Comment by liuyuan-pal** [comment]
crop size选240有点太大了，一般200会比较好。
![image](https://github.com/liuyuan-pal/SyncDreamer/assets/23974453/a14ff8b5-fd1b-4ddc-ad82-cf802974a746)

**Comment by yuedajiong** [comment]
https://github.com/liuyuan-pal/SyncDreamer/assets/52232153/df25f8a0-7d9a-41e1-b95b-cf60e99c6015

如果你要搞human的，我觉得3-5年都做不到metahuman那种效果。

这个mp4，是我：单图+动作文本产生的。  现在衣服和头发特别头发还差很多。      就这很soso的样子，其实可能是纯AI  sota的效果了。

**Comment by PikaCat-OuO** [comment]
> 这个mp4，是我：单图+动作文本产生的。 现在衣服和头发特别头发还差很多。 就这很soso的样子，其实可能是纯AI sota的效果了。
你这个视频是怎么生成出来的？

**Comment by yuedajiong** [comment]
我这个视频，是纯AI，但是是pipeline，多个step（目前就十多二十个了）的模型生成出来的，才到这样效果。
比如：背景去除，头发去除（不然女人的照片一般都有各种头发遮挡和饰物），衣服去除（裸体便于估计身材），人体关键点检测，人脸的检测于定位（这个从几个点到几百个点，用于后面 mesh render之后的对齐，然后反向去优化前面的重构），......，......,  ......,   后面是：头发的产生（不是mesh，是发束和特征，最后视频渲染用)，穿衣服，穿鞋子， 做文本驱动运动（眼珠，衣服，头发的发根固定但头发要拖动...)，   .........      (这好几十个步骤的背后的工作，严格的各种复合自然真实的约束，现在nerf+diffusion这种主流模式，三五年内都很难做到逼真。   比如头发和头皮的互作，头发搭载眼睛上要闭眼的等等）     我也只是对human做了这种很耗费人力的pipeline，其他所有的东西，我走的unified vision的路线（参见另外一个issue中的讨论）。

**Comment by PikaCat-OuO** [comment]
> 最终效果，可以达到的：就是你上面这样一张图，然后给定一些文本和参考视频描述，你这个模特，能够走几分钟T台，大家看不出来是AI合成的。

也就是说，可以做到单图直接生成非常逼真的人体3d模型（可以直接导入到游戏的那种），然后还可以驱动他做各种动作是吧

**Comment by yuedajiong** [comment]
是的。

走mesh那条路，只搞human:   人体人脸部分，走有模型smplx和10w+顶点的人脸的，然后合适的算法，可以驱动的比我哪个还好。就是算法多工作量大；  比较麻烦的是： 头发的自然和运动， 独立衣服的构造和着装和运动，动作逼真特别脸部表情眼睛的等。

对于任意对象，mesh那种case by case的不好搞，代价太大。

但现在nerf+diffu这种，要比较全的考虑：  特殊对象也统一，运动比k-plane那种还强，互作特别非刚体的互作，离游戏可用，还差的远。
