### ISSUE TITLE
Question about Correspondence between Camera Pose and Target Image 

### ISSUE THREAD

**Issue by kamzero** [liuyuan-pal/SyncDreamer#23]
Hi, 
Thanks for your wonderful work! 

During my exploration of the codebase, I noticed that the camera pose information is obtained from the meta_info/camera-16.pkl file, and it appears to be a fixed value for all objects. These poses are utilized in the construct_spatial_volume function. However, in the SyncDreamerTrainData module, the start_view_index is randomly selected, and the views are subsequently rearranged. This process determines the order of the target_images.

My question is: How does the rearranged order of target_images correspond to the respective poses? Given that the poses are fixed and the image order is randomized, I am curious to understand how the association between the rearranged target_images and the poses is maintained.

Thank you once again for your exceptional work, and I look forward to your reply on this matter.

Best regards

**Comment by liuyuan-pal** [comment]
Hi, the viewpoints form a circle and are uniformly distributed on the circle so that you may start from a random index to construct camera poses, which correspond to different world coordinate systems.

**Comment by kamzero** [comment]
Thank you for the clarification! I appreciate it.
