### ISSUE TITLE
How to unzip random view dataset

### ISSUE THREAD

**Issue by zhangfuyang** [liuyuan-pal/SyncDreamer#29]
Hi,

Thank you for uploading the full dataset!

I wonder how to unzip objaverse-renderings-random-part1.zip? It seems to be a multi-part archive. Should I concatenate part1.zip and part2.zip into a new zip and then unzip it? What are the part1.z01and part2.z01 files used for?

Thank you!

**Comment by liuyuan-pal** [comment]
Hi, I used bandizip to separately compressed the file into multiple files. You may just place them in the same dir and unzip the zip file directly.

**Comment by zhangfuyang** [comment]
![image](https://github.com/liuyuan-pal/SyncDreamer/assets/26685632/2240776f-da52-4760-8ae0-579d585d47b8)

Somehow I can't unzip the file directly.

**Comment by zhangfuyang** [comment]
I found the solution. In case anyone meets the same problem.

run: "zip -s- objaverse-renderings-random-part1.zip -O part1.zip", then "unzip part1.zip"

**Comment by liuyuan-pal** [comment]
> I found the solution. In case anyone meets the same problem.
> 
> run: "zip -s- objaverse-renderings-random-part1.zip -O part1.zip", then "unzip part1.zip"

Thanks for your information!
