### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by thucz** [liuyuan-pal/SyncDreamer#3]
Hi! I really appreciate your work! It is indeed insightful and useful for me! I believe it will have great impact on the related research in the community. 

I just noticed that you have uploaded your some files for inference. I wonder when you upload your training code as it is more convenient for me to deeply research based on that. Great thanks to your sharing!

Sincerely,
Zheng

**Comment by liuyuan-pal** [comment]
Hi, training codes will be available soon in several days. I'm still working on it. Thank you!

**Comment by thucz** [comment]
Thanks a lot!
