### ISSUE TITLE
Question about blender preprocessing

### ISSUE THREAD

**Issue by disercovery** [liuyuan-pal/SyncDreamer#33]
Why do you take a transpose on the rotation matrix [here](https://github.com/liuyuan-pal/SyncDreamer/blob/1fa5ecf118cbda2096978d27dd602d4d027e065d/blender_script.py#L209C9-L209C9)? I thought the obtained rotaion matrix is already world->camera so no need to take an inverse?

**Comment by liuyuan-pal** [comment]
Hi, I use the opencv-style world to camera pose. So an inverse is required here.

**Comment by Gynjn** [comment]
That you mean that code is convert blender W2C to openCV W2C style? 

Gentle ping @liuyuan-pal
