### ISSUE TITLE
GT mesh for GSO dataset

### ISSUE THREAD

**Issue by byeongjun-park** [liuyuan-pal/SyncDreamer#40]
Thanks for sharing your interesting work.
I can't find the GT mesh for the GSO dataset in the link you shared, am I missing something?

**Comment by liuyuan-pal** [comment]
hi, the link is here: https://connecthkuhk-my.sharepoint.com/:u:/g/personal/yuanly_connect_hku_hk/ESvAmPTCxdlBqouwaBZxvyEB13NH1iJEMvcjtlJIGjiTWQ?e=i8wVQz

**Comment by liuyuan-pal** [comment]
Hi, the meshes are saved at `gso-eval-meshes.zip` here https://connecthkuhk-my.sharepoint.com/:f:/g/personal/yuanly_connect_hku_hk/EjYHbCBnV-VPjBqNHdNulIABq9sYAEpSz4NPLDI72a85vw

**Comment by byeongjun-park** [comment]
I now know what to do. Thank you for your prompt response!!
