### ISSUE TITLE
About evaluation metric(CD)

### ISSUE THREAD

**Issue by TLB-MISS** [liuyuan-pal/SyncDreamer#44]
First of all, thank you for sharing this great work.

In the eval_mesh.py code, points are sampled from depth to compute the chamfer distance. Actually, I don't really understand this process. There is already a mesh, so why bother rendering the depth and re-sampling the point instead of directly sampling the point from it?

**Comment by TLB-MISS** [comment]
Does that make a fairer comparison between different methods (rather than sampling points directly from the mesh)?

**Comment by liuyuan-pal** [comment]
Thanks for the advice! 
Actually, I directly borrow the evaluation codes from my previous work here https://github.com/liuyuan-pal/NeRO/blob/3b4d421a646097e7d59557c5ea24f4281ab38ef1/eval_synthetic_shape.py#L87
I think sampling on the mesh is also feasible and fair.
