### ISSUE TITLE
About NVS metrics calculation

### ISSUE THREAD

**Issue by PikaCat-OuO** [liuyuan-pal/SyncDreamer#46]
I have a simple question that I still haven't figured out so far. When calculating metrics like PSNR, do you directly use the image output from the model to compare with the ground truth GSO images, or first go through the reconstruction process and render images from the reconstructed object and then compare with the ground truth?

**Comment by liuyuan-pal** [comment]
Hi, I use the generated views to calculate the PSNR instead of the rendering views.

**Comment by PikaCat-OuO** [comment]
Thanks, get it.😊

**Comment by PikaCat-OuO** [comment]
btw, regarding the input images, when evaluating metrics, do we directly use the first image i.e. "eval_samples/chicken-gt/000.jpg" as inputs?

**Comment by liuyuan-pal** [comment]
Yes, we use the first image as condition.
