### ISSUE TITLE
Where is the image to be embeded?

### ISSUE THREAD

**Issue by digbangbang** [liuyuan-pal/SyncDreamer#55]

**Comment by digbangbang** [comment]
Hi, I have seen the SyncDreamer/ldm/models/diffusion
/sync_dreamer.py  code. 
2 Questions left:
Fisrt,
In the training_step, the batch input maybe is like {target_image, input_image, elevation}, what is going to happen if I didn't have the target_image, since I see the 
https://github.com/liuyuan-pal/SyncDreamer/blob/bcad0f11b72c027cc4d0464918a7f6bb07ac26e5/ldm/models/diffusion/sync_dreamer.py#L380
allow the target_image is None.
Because I am doing some jobs like this 
https://github.com/dreamgaussian/dreamgaussian/blob/59f46d372f2448274a70624797678b1620f7faab/guidance/sd_utils.py#L137
It is just image, then goes training and return the loss.
The images input goes through the vae encoding process as the latent and use the unet as the noise pred. And the loss is made using the latent and the noise pred, I think I can use the syncdreamer for the same useage. Because I want to test the gaussian splatting with syncdreamer.
Second,
Does the model have the encoding process like vae like I mentioned above?

**Comment by liuyuan-pal** [comment]
Hi, this is the encoding step: https://github.com/liuyuan-pal/SyncDreamer/blob/bcad0f11b72c027cc4d0464918a7f6bb07ac26e5/ldm/models/diffusion/sync_dreamer.py#L385C34-L385C34
Actually, we fixed the viewpoints so it may not be feasible to apply SDS to syncdreamer again.
