### ISSUE TITLE
How much VRAM need for inference?

### ISSUE THREAD

**Issue by Hangsiin** [liuyuan-pal/SyncDreamer#6]
I tried to inference in google colab environment with T4 GPU (16GB VRAM) and Cuda OOM error came out.
Is there any appropriate requirement for VRAM?

**Comment by liuyuan-pal** [comment]
Hi, you may try `--sample_num 1` and `--batch_view_num 4`, which means we only sample 1 instance (16 images) and on every step, we only denoise 4 images, which would greatly reduce the required memories. However, this would be much slower in generation.

**Comment by Hangsiin** [comment]
Thanks for the answer.
It worked!

**Comment by mshahbazi72** [comment]
Hi

I am getting out-of-memory errors when training Neus. I'm using the default config and the command provided in the repo. I am running the code on a GPU with 24G memory.

Do you have any suggestions on how to resolve the OOM error?
